# keymapping for default view
[default_view]
keymap = [
    { keys = [ "Q" ], command = "quit --output-current-directory" },
    # ...
]

# keymapping for task view
[task_view]
keymap = [
    # ...
]

# keymapping for help view
[help_view]
keymap = [
    # ...
]
